import { useEffect, useState } from "react";
import {
  AlertTriangle,
  Bell,
  Car,
  CheckCircle2,
  Clock3,
  MapPin,
  ShieldAlert,
} from "lucide-react";

import { api } from "../services/api";
import type { Alert as AlertType } from "../services/api";


function severityStyle(severity: string) {
  if (severity === "CRITICAL") {
    return "border-red-500/30 bg-red-500/5 text-red-400";
  }

  if (severity === "HIGH") {
    return "border-orange-500/30 bg-orange-500/5 text-orange-400";
  }

  return "border-yellow-500/20 bg-yellow-500/5 text-yellow-400";
}

function severityIcon(severity: string) {
  if (severity === "CRITICAL") {
    return <ShieldAlert size={17} />;
  }

  return <AlertTriangle size={17} />;
}

export default function Alerts() {
  const [alerts, setAlerts] = useState<AlertType[]>([]);

  useEffect(() => {
    api.getAlerts().then(setAlerts).catch(console.error);
  }, []);

  return (
    <div className="space-y-8">
      {/* HEADER */}
      <div className="flex items-end justify-between">
        <div>
          <p className="text-xs font-semibold tracking-[0.28em] text-red-400">
            INTELLIGENCE RESPONSE
          </p>

          <h1 className="mt-2 text-3xl font-semibold tracking-tight">
            Alert Center
          </h1>

          <p className="mt-2 text-sm text-slate-500">
            AI-generated alerts requiring operator attention.
          </p>
        </div>

        <div className="flex items-center gap-2 rounded-lg border border-red-500/20 bg-red-500/5 px-4 py-2.5">
          <Bell size={15} className="text-red-400" />
          <span className="text-xs font-medium text-red-300">
            {alerts.filter(
              (alert) =>
                !alert.is_resolved &&
             alert.severity.toLowerCase() === "high"
          ).length} HIGH PRIORITY
          </span>
        </div>
      </div>

      {/* SUMMARY */}
      <div className="grid grid-cols-4 gap-4">
        <div className="rounded-xl border border-[#1B2330] bg-[#0D111A] p-5">
          <p className="text-xs text-slate-500">ACTIVE ALERTS</p>
          <p className="mt-3 text-3xl font-semibold">
            {alerts.filter((alert) => !alert.is_resolved).length}
            </p>
        </div>

        <div className="rounded-xl border border-red-500/20 bg-[#0D111A] p-5">
          <p className="text-xs text-slate-500">CRITICAL</p>
          <p className="mt-3 text-3xl font-semibold text-red-400">
            {alerts.filter((alert) => alert.severity.toLowerCase() === "critical").length}
          </p>
        </div>

        <div className="rounded-xl border border-orange-500/20 bg-[#0D111A] p-5">
          <p className="text-xs text-slate-500">HIGH</p>
          <p className="mt-3 text-3xl font-semibold text-orange-400">
            {alerts.filter((alert) => alert.severity.toLowerCase() === "high").length}
          </p>
        </div>

        <div className="rounded-xl border border-[#1B2330] bg-[#0D111A] p-5">
          <p className="text-xs text-slate-500">ACKNOWLEDGED</p>
          <p className="mt-3 text-3xl font-semibold text-slate-300">
            {alerts.filter((alert) => alert.is_resolved).length}
          </p>
        </div>
      </div>

      {/* ALERT LIST */}
      <div className="overflow-hidden rounded-xl border border-[#1B2330] bg-[#0D111A]">
        <div className="border-b border-[#1B2330] px-6 py-5">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="font-semibold">Recent Alerts</h2>
              <p className="mt-1 text-xs text-slate-500">
                Latest intelligence events generated by the platform.
              </p>
            </div>

            <span className="text-xs text-slate-600">
              LIVE FEED
            </span>
          </div>
        </div>

        <div className="divide-y divide-[#1B2330]">
          {alerts.map((alert) => (
            <div
              key={alert.id}
              className="px-6 py-5 transition hover:bg-[#101722]"
            >
              <div className="flex items-center justify-between">
                {/* LEFT */}
                <div className="flex items-center gap-5">
                  <div
                    className={`flex h-10 w-10 items-center justify-center rounded-lg border ${severityStyle(
                      alert.severity
                    )}`}
                  >
                    {severityIcon(alert.severity)}
                  </div>

                  <div>
                    <div className="flex items-center gap-3">
                      <span className="font-mono text-sm font-semibold text-slate-100">
                        {alert.plate_number}
                      </span>

                      <span className="text-xs text-slate-600">
                        {alert.id}
                      </span>

                      <span
                        className={`rounded-md border px-2 py-1 text-[9px] font-semibold tracking-wider ${severityStyle(
                          alert.severity.toUpperCase()
                        )}`}
                      >
                        {alert.severity.toUpperCase()}
                      </span>
                    </div>

                    <p className="mt-1 text-sm text-slate-400">
                      {alert.message}
                    </p>

                    <div className="mt-2 flex items-center gap-4 text-xs text-slate-600">
                      <span className="flex items-center gap-1.5">
                        <MapPin size={12} />
                        Ahmedabad
                      </span>

                      <span className="flex items-center gap-1.5">
                        <CameraIcon />
                        Ahmedabad Camera 01
                      </span>

                      <span className="flex items-center gap-1.5">
                        <Clock3 size={12} />
                        {new Date(alert.created_at).toLocaleString()}
                      </span>
                    </div>
                  </div>
                </div>

                {/* RIGHT */}
                <div className="flex items-center gap-8">
                  <div className="text-right">
                    <p className="text-[10px] tracking-wider text-slate-600">
                      ANPR CONFIDENCE
                    </p>

                    <p className="mt-1 text-sm font-medium text-slate-300">
                      95%
                    </p>
                  </div>

                  <div className="text-right">
                    <p className="text-[10px] tracking-wider text-slate-600">
                      STATUS
                    </p>

                    <div className="mt-1 flex items-center gap-1.5 text-xs">
                      {alert.is_resolved ? (
                        <>
                          <CheckCircle2 size={13} className="text-emerald-400" />
                          <span className="text-emerald-400">
                            ACKNOWLEDGED
                          </span>
                        </>
                      ) : (
                        <>
                          <AlertTriangle size={13} className="text-red-400" />
                          <span className="text-red-400">
                            UNRESOLVED
                          </span>
                        </>
                      )}
                    </div>
                  </div>

                  <button className="rounded-lg border border-[#1B2330] bg-[#080B12] px-4 py-2 text-xs font-medium text-slate-300 transition hover:border-blue-500/40 hover:text-white">
                    Investigate
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function CameraIcon() {
  return <Car size={12} />;
}